# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo_app.Project'),
        ),
    ]
